# Generated by Django 4.1.1 on 2022-10-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myBlog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="blog"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_comments",
                to="myBlog.post",
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to="myBlog.post",
            ),
        ),
    ]
