# Generated by Django 4.1.1 on 2022-10-12 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myMusicApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="file_url",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="music",
                validators=[django.core.validators.FileExtensionValidator(["mp3"])],
            ),
        ),
    ]
