# Generated by Django 4.1.1 on 2022-10-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myMusicApp", "0003_album_image_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="image_song",
            field=models.ImageField(blank=True, null=True, upload_to="music"),
        ),
    ]
