# Generated by Django 4.1.1 on 2022-10-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myAuth", "0003_profile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images"),
        ),
    ]
