# Generated by Django 4.1.1 on 2022-10-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myAuth", "0002_alter_profile_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(blank=True, default="M", max_length=1, null=True),
        ),
    ]
